### ISSUE TITLE
Add a musl binary to releases

### ISSUE THREAD

**Issue by romanlevin** [egnyte/ax#12]
Might be useful when debugging on Alpine Linux boxes.

**Comment by zefhemel** [comment]
That'd be nice. I wish there was just a simple env variable to set for this like for other architectures, but doesn't look that way: https://www.reddit.com/r/golang/comments/4cxrcv/whats_the_proper_way_to_build_golang_apps_for/

**Comment by romanlevin** [comment]
Yeah, you basically have to build it inside a docker container running Alpine.

Doesn't seem like GoReleaser supports it, either.

**Comment by zefhemel** [comment]
Not as far as a simple Google search could tell me, no.

**Comment by zefhemel** [comment]
Since nobody at Egnyte cares about this anymore, closing :)
